language: go
go:
- 1.13
env:
  global:
  - GOOS=linux
install:
- go build .
script:
- md5sum docker-zfs-plugin > md5.txt
- sha256sum docker-zfs-plugin > sha256.txt
- sha512sum docker-zfs-plugin > sha512.txt
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZM6Tp7y+wfEchMoGngiMxClRIWpv8eBA+2y8NqO61LHgsse0rS0NA+0qWtQJkq/B6ZybxvUlCRNbIZVrYGlWYO20ymXuSKsmIVmTJWT9ZF8spr9FnIpCDUse+Wr4sDjL87MA4an1rnRxPRT5Je/5PWi70AIBXFi5ik/gES+LCA6zqp2/Urm7k/Q76a4698AnXiPj3iMlGDInDOEIqjh/dKJCz1npFpm5qNbh19bZ+POvzejFLITUdrC4CaOzheM2jLTNIEpDiwSqRWl3RsO5kB7PR2+2bFKZa72dj944YV56Jqso3uUw/Sm0xL/rBI5ONJzGBpiXDYqrccTLCyE7+I1Osp2Vn7i5PYPjkvLyQESAfv7zjr3HsipKEeXBdoZpqIJeUY7963BlQCOoZ9ejNm/kld+HQ6+TaBv64wJmZdtpugPeyf/SYPrW5Em7m5nP0/LMXme2pT3AfZwAmziPFDw/FIzZoF39NIJfgiFY5oaonwY8icW7+quuobPLr7o1q5YJv8TVJGYfA/pbHKr4EX93NyUDcCC8aH3rah3I9jexkooR17oBu8zo2nM+L72JO2uO+9VTt6UQKPcMtfVQSTsgYav7Vb+vsQfdzvb9JMfIYubXWKjz/Sig7LcCLAe500jPVzTcu9+L08dCFd7znBR7dg0Rs8loqwsssn4tMr0=
  file:
  - docker-zfs-plugin
  - md5.txt
  - sha256.txt
  - sha512.txt
  on:
    tags: true
